branch-defaults:
  default:
    environment: mainenv
    group_suffix: null
global:
  application_name: mainapi
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.6 running on 64bit Amazon Linux
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
